version: '3.8'

services:
  # --- 1. DATABASES & BROKERS ---
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # CHANGED: 5433 on the outside maps to 5432 on the inside
  redis-cache:
    image: redis:alpine
    ports:
      - "6380:6379" # CHANGED: 6380 on the outside maps to 6379 on the inside

  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"   # CHANGED to 5673
      - "15673:15672" # CHANGED to 15673

  # --- 2. MICROSERVICES ---
  identity-provider:
    build: ./identity-provider
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres-db # Docker networking automatically resolves this name!
    depends_on:
      - postgres-db

  stock-service:
    build: ./stock-service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=postgres-db
      - REDIS_URL=redis://redis-cache:6379
    depends_on:
      - postgres-db
      - redis-cache

  order-gateway:
    build: ./order-gateway
    ports:
      - "3003:3003"
    environment:
      - REDIS_URL=redis://redis-cache:6379
      - RABBITMQ_URL=amqp://rabbitmq-broker
    depends_on:
      - redis-cache
      - rabbitmq-broker

  notification-hub:
    build: ./notification-hub
    ports:
      - "3004:3004"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq-broker
    depends_on:
      - rabbitmq-broker

  kitchen-queue:
    build: ./kitchen-queue
    ports:
      - "3005:3005"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq-broker
    depends_on:
      - rabbitmq-broker

  # --- 3. FRONTEND ---
  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Maps your browser's port 3000 to Nginx's port 80