name: CI Build Check

# This tells the robot to wake up every time you push to the 'main' branch
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The temporary cloud computer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Test Docker Compose Build
      # This forces GitHub to build your 6 microservices to prove they compile
      run: docker compose build